# Generated by Django 4.1.1 on 2022-09-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsettings',
            name='available_booking_months',
            field=models.IntegerField(blank=True, default=1, help_text='if 2, user can only book booking for next two months.'),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='booking_enable',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='confirmation_required',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='disable_weekend',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='max_booking_per_time',
            field=models.IntegerField(blank=True, default=1, help_text='Quantas vezes pode agendar no mesmo.'),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='period_of_each_booking',
            field=models.CharField(blank=True, choices=[('5', '5M'), ('10', '10M'), ('15', '15M'), ('20', '20M'), ('25', '25M'), ('30', '30M'), ('35', '35M'), ('40', '40M'), ('45', '45M'), ('60', '1H'), ('75', '1H 15M'), ('90', '1H 30M'), ('105', '1H 45M'), ('120', '2H'), ('150', '2H 30M'), ('180', '3H')], default='30', help_text='Intervalo entre os agendamentos', max_length=3),
        ),
    ]
